### ISSUE TITLE
Doc enhancement: readthedocs examples broken

### ISSUE THREAD

**Issue by jjennings955** [rmorshea/idom#147]
The examples at https://idom.readthedocs.io/en/latest/examples.html seem to be based on an older version of code and there are some API changes that break many (maybe all?) of them.

For example in the To Do List example creates callbacks for events like this:
```python
task_input = idom.html.input(onKeyDown=add_new_task)

... ...

delete_button = idom.html.td(idom.html.button("x"), onClick=remove)
```
but the current API has you pass the callbacks as a dictionary 

Something like:
```python
task_input = idom.html.input({'onKeyDown':add_new_task})
```

**Comment by rmorshea** [comment]
Thanks @jjennings955 I'd completely forgotten about that.
